# Generated by Django 2.1.1 on 2018-11-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Dil Adı')),
                ('kod', models.CharField(max_length=4, null=True, verbose_name='Dil Kodu')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Dil Url Adı')),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
                'db_table': 'diller',
            },
        ),
    ]
