# Generated by Django 2.1.1 on 2018-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_maas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maas',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, verbose_name='Maaş Url Adı'),
        ),
    ]
