# Generated by Django 2.1.1 on 2018-11-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20181113_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Meslek Adı')),
                ('aciklama', models.TextField(blank=True, default='', null=True, verbose_name='Açıkalama')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Meslek Url Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Meslek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Meslek Adı')),
                ('aciklama', models.TextField(blank=True, default='', null=True, verbose_name='Açıkalama')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Meslek Url Adı')),
            ],
            options={
                'verbose_name': 'Meslek',
                'verbose_name_plural': 'Meslekler',
                'db_table': 'meslekler',
            },
        ),
    ]
