# Generated by Django 2.1.1 on 2018-11-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_sehir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sehir',
            options={'ordering': ['plaka'], 'verbose_name': 'Şehir', 'verbose_name_plural': 'Şehirler'},
        ),
    ]
