# Generated by Django 2.1.1 on 2018-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20181113_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askerlik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(blank=True, default='', null=True, verbose_name='Askerlik Seçeneği')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Seçenek Url Adı')),
            ],
            options={
                'verbose_name': 'Askerlik Durumu',
                'verbose_name_plural': 'Askerlik Durumları',
                'db_table': 'askerlik_durumlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(blank=True, default='', null=True, verbose_name='Eğitim Seviye Başlığı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Eğitim Url Adı')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitim Seviyeleri',
                'db_table': 'egitim_seviyeleri',
                'ordering': ['id'],
            },
        ),
    ]
