# Generated by Django 2.1.1 on 2018-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_askerlik_egitim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(blank=True, default='', null=True, verbose_name='Askerlik Seçeneği')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Seçenek Url Adı')),
            ],
            options={
                'verbose_name': 'Mesai Süresi',
                'verbose_name_plural': 'Mesai Süreleri',
                'db_table': 'mesali_sureleri',
                'ordering': ['id'],
            },
        ),
    ]
