# Generated by Django 2.1.1 on 2018-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askerlik',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Askerlik Seçeneği'),
        ),
        migrations.AlterField(
            model_name='egitim',
            name='baslik',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Eğitim Seviye Başlığı'),
        ),
        migrations.AlterField(
            model_name='sehir',
            name='plaka',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Plaka'),
        ),
    ]
