# Generated by Django 2.1.1 on 2018-11-20 23:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20181121_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Sayfa Adı')),
                ('slug', models.SlugField(blank=True, default='', max_length=255, verbose_name='Url Yazısı')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('durum', models.BooleanField(default=True, verbose_name='Sayfayı Yayımla')),
                ('detay', ckeditor.fields.RichTextField(default='', verbose_name='İçerik')),
                ('c_time', models.DateTimeField(auto_now=True, verbose_name='Oluşturulma')),
                ('u_time', models.DateTimeField(auto_now_add=True, verbose_name='Güncellenme')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('trash', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'db_table': 'sayfalar',
            },
        ),
    ]
