# Generated by Django 2.1.1 on 2018-11-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0006_auto_20181113_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Firma url adı')),
                ('telefon', models.CharField(max_length=20, verbose_name='Firma Telefon No')),
                ('eposta', models.EmailField(max_length=255, verbose_name='E-post adresi')),
                ('yetkili', models.CharField(max_length=255, verbose_name='Firma Yetkilisi')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Firma Adresi')),
                ('aciklama', models.TextField(verbose_name='Firma Açıklaması')),
                ('vergi_no', models.CharField(max_length=255, verbose_name='Vergi Numarası')),
                ('vergi_dairesi', models.CharField(max_length=255, verbose_name='Vergi Dairesi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Kategori', verbose_name='Kategori')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'db_table': 'firmalar',
            },
        ),
    ]
