# Generated by Django 2.1.1 on 2018-11-20 21:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0008_zaman'),
        ('is', '0003_auto_20181120_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='İstek Başlığı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='İstek başlığı url adı')),
                ('tecrube', models.CharField(choices=[('F', 'Farketmez'), ('az', '1 yıldan az'), ('1-3', '1-3 yıl'), ('3-5', '3-5 yıl'), ('5-10', '5-10 yıl'), ('deneyimli', '10 yıldan fazla')], default='F', max_length=11, verbose_name='Deneyim')),
                ('detay', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Detay')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Eklenme Tarihi')),
                ('u_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('durum', models.BooleanField(default=True, verbose_name='Yayımlanma')),
                ('kategori', models.ManyToManyField(to='system.Kategori', verbose_name='İş Kategorisi')),
                ('maas', models.ManyToManyField(to='system.Maas', verbose_name='İstenen Maaş')),
                ('meslek', models.ManyToManyField(to='system.Meslek', verbose_name='Meslek')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Çalışılacak Şehir')),
                ('uye', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaman', models.ManyToManyField(to='system.Zaman', verbose_name='İş Kategorisi')),
            ],
            options={
                'verbose_name': 'İş isteği',
                'verbose_name_plural': 'İş istekleri',
                'db_table': 'istekler',
            },
        ),
        migrations.AlterModelOptions(
            name='ilan',
            options={'verbose_name': 'İş ilanı', 'verbose_name_plural': 'İş ilanları'},
        ),
        migrations.RenameField(
            model_name='ilan',
            old_name='ayrintilar',
            new_name='detay',
        ),
        migrations.AddField(
            model_name='firma',
            name='durum',
            field=models.BooleanField(default=False, verbose_name='Onaylanmış'),
        ),
        migrations.AddField(
            model_name='ilan',
            name='durum',
            field=models.BooleanField(default=True, verbose_name='Yayımlanma'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='zaman',
            field=models.ManyToManyField(to='system.Zaman', verbose_name='Çalışma Zamanı'),
        ),
    ]
