# Generated by Django 2.1.1 on 2018-11-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0005_remove_firma_eposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='eposta',
            field=models.EmailField(default=None, max_length=255, null=True, verbose_name='E-post adresi'),
        ),
    ]
