# Generated by Django 2.1.1 on 2018-11-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is', '0006_firma_eposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='uye',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='askerlik',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='dil_konusma',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='dil_yazma',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='egitim',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='maas',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='meslek',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='ilan',
            name='zaman',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='maas',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='meslek',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='uye',
        ),
        migrations.RemoveField(
            model_name='istek',
            name='zaman',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Ilan',
        ),
        migrations.DeleteModel(
            name='Istek',
        ),
    ]
