"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7-f5y3z#h!jupxz^7*g+5_jzfgozmop7qqkp9u98$=i5#z=f^='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #KULLANDIĞIM EKLENTİLER
    'ckeditor',
    #'ckeditor_uploader',
    'django_cleanup',
    'stdimage',
    'crispy_forms',
    #'captcha',

    #UYGULAMALARIM
    'user',
    'system',
    #'is',
    'ilan',
]
AUTH_USER_MODEL = 'user.Uye'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'views') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.dakikada_contents'
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'tr'
TIME_ZONE = 'Europe/Istanbul'
USE_I18N = True
USE_L10N = True
USE_TZ = True



STATICFILES_DIRS = [ os.path.join(BASE_DIR, "assets/") ]
STATIC_URL = '/assets/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'assets/')

MEDIA_ROOT  = os.path.join(BASE_DIR, 'media')
MEDIA_URL   = '/media/'

CRISPY_TEMPLATE_PACK = "bootstrap4"

CKEDITOR_JQUERY_URL = os.path.join(STATIC_URL, 'js/jquery-3.2.1.min.js')
CKEDITOR_UPLOAD_PATH = os.path.join( MEDIA_ROOT, 'uploads' )
CKEDITOR_IMAGE_BACKEND = "Pillow"
CKEDITOR_CONFIGS = {
    'default': {
        #'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            {'name': 'basicstyles',
             'items': [ 'Bold', 'Italic', 'Underline', 'HorizontalRule', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']}
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Maximize', 'Source']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'basicstyles',
             'items': [ 'Bold',
                        'Italic',
                        'Underline',
                        'Link',
                        'Unlink',
                        'Image',
                        'HorizontalRule',
                        """'Subscript', 'Superscript',"""
                        'RemoveFormat']},
            {'name': 'styles', 'items': ['FontSize']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']}


        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
         'height': 450,
         'width': '100%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            #'uploadimage', # the upload image feature
            # your extra plugins here
            #'div',
            'autolink',
            #'autoembed',
            'embedsemantic',
            #'autogrow',
            # 'devtools',
            #'widget',
            #'lineutils',
            #'clipboard',
            #'dialog',
            #'dialogui',
            #'elementspath'
        ]),
    },

    'members': {
        'toolbar_basit': [
            {'name': 'basicstyles',
             'items': [ 'Bold', 'Italic', 'Underline', 'HorizontalRule', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']}
        ],
        'toolbar': 'basit',
         'height': 200,
         'width': '100%',
        'tabSpaces': 4,
    }
}

"""
RECAPTCHA_PUBLIC_KEY = '6Le-L0AUAAAAADmb870GW5M2_n6eQ3vyxydY1w1x'
RECAPTCHA_PRIVATE_KEY = '6Le-L0AUAAAAALZXQ865kUGY55-4tje56_GXvhME'
RECAPTCHA_PROXY = 'http://127.0.0.1:8000'
NOCAPTCHA = True
"""

TECRUBE_OPTIONS = ((0, 'Farketmez'), (1, '1 yıldan az'), (2, '1-3 yıl'), (3, '3-5 yıl'), (4, '5-10 yıl'), (5, '10 yıldan fazla'))
