# Generated by Django 2.1.1 on 2018-11-22 00:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0010_sayfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='Firma url adı')),
                ('telefon', models.CharField(max_length=20, verbose_name='Firma Telefon No')),
                ('eposta', models.EmailField(default=None, max_length=255, null=True, verbose_name='E-post adresi')),
                ('yetkili', models.CharField(max_length=255, verbose_name='Firma Yetkilisi')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Firma Adresi')),
                ('aciklama', models.TextField(verbose_name='Firma Açıklaması')),
                ('vergi_no', models.CharField(max_length=255, verbose_name='Vergi Numarası')),
                ('vergi_dairesi', models.CharField(max_length=255, verbose_name='Vergi Dairesi')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Eklenme Tarihi')),
                ('u_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('durum', models.BooleanField(default=False, verbose_name='Onaylanmış')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Kategori', verbose_name='Kategori')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Şehir')),
                ('uye', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'db_table': 'firmalar',
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='İlan Başlığı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='İlan url adı')),
                ('tecrube', models.CharField(choices=[('F', 'Farketmez'), ('az', '1 yıldan az'), ('1-3', '1-3 yıl'), ('3-5', '3-5 yıl'), ('5-10', '5-10 yıl'), ('deneyimli', '10 yıldan fazla')], default='F', max_length=11, verbose_name='Deneyim')),
                ('cinsiyet', models.CharField(choices=[('F', 'Farketmez'), ('E', 'Erkek'), ('K', 'Kadın')], default='F', max_length=1, verbose_name='Cinsiyet')),
                ('yas_min', models.SmallIntegerField(default=18, verbose_name='Minimum Yaş')),
                ('yas_max', models.SmallIntegerField(default=45, verbose_name='Maximum Yaş')),
                ('detay', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='İş Tanıtım Yazısı')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Eklenme Tarihi')),
                ('u_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('durum', models.BooleanField(default=True, verbose_name='Yayımlanma')),
                ('askerlik', models.ManyToManyField(to='system.Askerlik', verbose_name='Askerlik Durumu')),
                ('dil_konusma', models.ManyToManyField(blank=True, default=None, null=True, related_name='konusulan_diller', to='system.Dil', verbose_name='Konuşulabilen Diller')),
                ('dil_yazma', models.ManyToManyField(blank=True, default=None, null=True, related_name='yazilan_diller', to='system.Dil', verbose_name='Yazılıp, Okunabilen Diller')),
                ('egitim', models.ManyToManyField(to='system.Egitim', verbose_name='Eğitim Seviyesi')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilan.Firma', verbose_name='Çalışılacak Firma')),
                ('kategori', models.ManyToManyField(to='system.Kategori', verbose_name='İş Kategorisi')),
                ('maas', models.ManyToManyField(to='system.Maas', verbose_name='Muhtemel Maaş')),
                ('meslek', models.ManyToManyField(to='system.Meslek', verbose_name='Meslek')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Çalışılacak Şehir')),
                ('zaman', models.ManyToManyField(to='system.Zaman', verbose_name='Çalışma Zamanı')),
            ],
            options={
                'verbose_name': 'İş ilanı',
                'verbose_name_plural': 'İş ilanları',
                'db_table': 'ilanlar',
            },
        ),
        migrations.CreateModel(
            name='Istek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='İstek Başlığı')),
                ('slug', models.SlugField(editable=False, max_length=255, null=True, verbose_name='İstek başlığı url adı')),
                ('tecrube', models.CharField(choices=[('F', 'Farketmez'), ('az', '1 yıldan az'), ('1-3', '1-3 yıl'), ('3-5', '3-5 yıl'), ('5-10', '5-10 yıl'), ('deneyimli', '10 yıldan fazla')], default='F', max_length=11, verbose_name='Deneyim')),
                ('detay', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Detay')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Eklenme Tarihi')),
                ('u_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi')),
                ('durum', models.BooleanField(default=True, verbose_name='Yayımlanma')),
                ('kategori', models.ManyToManyField(to='system.Kategori', verbose_name='İş Kategorisi')),
                ('maas', models.ManyToManyField(to='system.Maas', verbose_name='İstenen Maaş')),
                ('meslek', models.ManyToManyField(to='system.Meslek', verbose_name='Meslek')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Çalışılacak Şehir')),
                ('uye', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaman', models.ManyToManyField(to='system.Zaman', verbose_name='İş Kategorisi')),
            ],
            options={
                'verbose_name': 'İş isteği',
                'verbose_name_plural': 'İş istekleri',
                'db_table': 'istekler',
            },
        ),
    ]
