# Generated by Django 2.1.1 on 2018-11-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0002_auto_20181123_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istek',
            name='zaman',
            field=models.ManyToManyField(to='system.Zaman', verbose_name='Zaman'),
        ),
    ]
