# Generated by Django 2.1.1 on 2018-11-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_sayfa'),
        ('ilan', '0003_auto_20181123_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istek',
            name='meslek',
        ),
        migrations.AddField(
            model_name='istek',
            name='meslek',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Meslek', verbose_name='Meslek'),
        ),
    ]
