# Generated by Django 2.1.1 on 2018-11-29 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0004_auto_20181123_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Firma Tanıtım Yazısı'),
        ),
    ]
