# Generated by Django 2.1.1 on 2018-11-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0005_auto_20181129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='kategori',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='system.Kategori', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='sehir',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Firma Telefon No'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='vergi_dairesi',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='vergi_no',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Vergi Numarası'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkili',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Firma Yetkilisi'),
        ),
    ]
