# Generated by Django 2.1.1 on 2018-11-29 17:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0007_auto_20181129_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Firma Tanıtım Yazısı'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='sehir',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='yetkili',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Firma Yetkilisi'),
        ),
    ]
