# Generated by Django 2.1.1 on 2018-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0008_auto_20181129_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='adres',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Firma Adresi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='eposta',
            field=models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-post adresi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='telefon',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Firma Telefon No'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='vergi_dairesi',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='firma',
            name='vergi_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Vergi Numarası'),
        ),
    ]
