# Generated by Django 2.1.1 on 2018-12-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0009_auto_20181129_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilan',
            options={'ordering': ['-id'], 'verbose_name': 'İş ilanı', 'verbose_name_plural': 'İş ilanları'},
        ),
    ]
