# Generated by Django 2.1.1 on 2018-12-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0011_remove_istek_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istek',
            name='meslek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Meslek', verbose_name='Meslek'),
        ),
    ]
