# Generated by Django 2.1.1 on 2018-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0012_auto_20181209_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='tecrube',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Farketmez'), (1, '1 yıldan az'), (2, '1-3 yıl'), (3, '3-5 yıl'), (4, '5-10 yıl'), (5, '10 yıldan fazla')], default=0, max_length=11, verbose_name='Deneyim'),
        ),
        migrations.AlterField(
            model_name='istek',
            name='tecrube',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Farketmez'), (1, '1 yıldan az'), (2, '1-3 yıl'), (3, '3-5 yıl'), (4, '5-10 yıl'), (5, '10 yıldan fazla')], default=0, max_length=11, verbose_name='Deneyim'),
        ),
    ]
