# Generated by Django 2.1.1 on 2018-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181113_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='tcno',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
