# Generated by Django 2.1.1 on 2018-11-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181113_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='askerlik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Askerlik', verbose_name='Askerlik Durumu'),
        ),
        migrations.AlterField(
            model_name='uye',
            name='egitim',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Egitim', verbose_name='Egitim Durumu'),
        ),
    ]
