# Generated by Django 2.1.1 on 2018-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181120_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='c_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Eklenme Tarihi'),
        ),
        migrations.AddField(
            model_name='uye',
            name='u_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
