# Generated by Django 2.1.1 on 2018-11-21 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_sayfa'),
        ('user', '0006_auto_20181120_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='sehir',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Sehir', verbose_name='Şehir'),
        ),
    ]
