# Generated by Django 2.1.1 on 2018-11-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_uye_sehir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='eposta',
            field=models.EmailField(default=True, max_length=254, null=True, unique=True, verbose_name='E-posta Adresi'),
        ),
    ]
