# Generated by Django 2.1.1 on 2018-11-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181128_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='tcno',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='TC Kimlik No'),
        ),
    ]
