# Generated by Django 2.1.1 on 2018-11-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181129_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uye',
            name='uye_tipi',
            field=models.CharField(blank=True, choices=[('kullanici', 'Kullanıcı'), ('is_veren', 'İş Veren')], default='kullanici', max_length=15, null=True, verbose_name='Üyelik Durumu'),
        ),
    ]
