# Generated by Django 2.1.1 on 2018-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_sayfa'),
        ('user', '0012_auto_20181129_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='uye',
            name='dil_konusma',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='konusulabilen_diller', to='system.Dil', verbose_name='Konuşabildiğiniz Diller'),
        ),
        migrations.AddField(
            model_name='uye',
            name='dil_yazma',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='yazilabilen_diller', to='system.Dil', verbose_name='Yazıp, Okuyabildiğiniz Diller'),
        ),
    ]
